## Website Tasks Overview

| Web Archives     | Task 1                                                                                                              | Task 2                                                                                                                                       |
|------------------|---------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------|
| Wayback Machine  | Find and access the archived snapshot or memento of the Yahoo homepage layout from January 1, 2018.                 | Locate and access a snapshot or memento of the Wikipedia homepage for a different specific date after retrieving the Yahoo homepage snapshot. |
| UK Web Archive   | Retrieve precise product page information of an item that trended on Amazon in September 2019.                     | Locate and access a snapshot or memento of the Google homepage on March 15th, 2005 after retrieving the Amazon product page snapshot.        |
| Trove            | Visit a sports-related newspaper from April 15, 2005.                                                               | Locate and access a snapshot or memento related to weather in 1990 after retrieving the sports-related newspaper snapshot.                    |
| Pandora          | Get information or descriptions of the "www.environment.gov.au" website in 2009.                                   | Locate and access a snapshot or memento of the www.scew.gov.au homepage for the year 2012 after retrieving information about the "www.environment.gov.au" website. |
| Archive.today    | Retrieve playlist compilations or song suggestions from a certain date on Spotify (e.g., browse the "Top 50 Hits" playlist on January 1, 2020). | Locate and access a snapshot or memento of the YouTube homepage on April 15th, 2009 after retrieving Spotify playlist information.          |
